CREATE DATABASE HOSPITAL;
GO
USE HOSPITAL;
GO

CREATE TABLE CONSULTORIO(
	no_consultorio INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	activo BIT NOT NULL,
	tipo VARCHAR(30)
);
GO

CREATE TABLE ESTADO_CITA(
	id_estado INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	estado VARCHAR(40) NOT NULL
);
GO

CREATE TABLE ESPECIALIDAD(
	id_especialidad INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(35) NOT NULL,
	tiempo_min_cita INT NOT NULL
);
GO

CREATE TABLE SERVICIO(
	id_servicio INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(35),
	detalles VARCHAR(35),
	precio DECIMAL(10,2) NOT NULL
);
GO

CREATE TABLE MEDICAMENTO(
	id_medicamento INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nombre VARCHAR(35) NOT NULL,
	detalles VARCHAR(50) NOT NULL,
	precio DECIMAL(10,2) NOT NULL,
	stock INT NOT NULL,
	presentacion VARCHAR(20) NOT NULL
);
GO

CREATE TABLE USUARIO(
	correo VARCHAR(64) NOT NULL PRIMARY KEY,
	contrasenia VARCHAR(20) NOT NULL,
	tipo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE PACIENTE(
	id_paciente INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	nacimiento DATE NOT NULL,
	primer_nombre VARCHAR(30) NOT NULL,
	segundo_nombre VARCHAR(30) NULL,
	a_paterno VARCHAR(30) NOT NULL,
	a_materno VARCHAR(30) NULL,
	tipo_sangre VARCHAR(5) NOT NULL,
	donante BIT NOT NULL,
	sexo VARCHAR(15) NOT NULL,
	fracturas VARCHAR(30) NULL,
	telefono VARCHAR(13) NOT NULL,
	alergias VARCHAR(30) NULL,
	correo VARCHAR(64) NOT NULL,

	CONSTRAINT FK_USUARIO_PACIENTE FOREIGN KEY(correo)
	REFERENCES USUARIO (correo)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE EMPLEADO(
	id_empleado INT IDENTITY(1,1) PRIMARY KEY,
	genero VARCHAR(15) NOT NULL,
	curp VARCHAR(18) NOT NULL,
	primer_nom_emp VARCHAR(30) NOT NULL,
	segundo_nom_emp VARCHAR(30) NULL,
	a_pat_emp VARCHAR(30) NOT NULL,
	a_mat_emp VARCHAR(30) NULL,
	telefono VARCHAR(13) NOT NULL,
	correo VARCHAR(64) NOT NULL,

	CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY(correo)
	REFERENCES USUARIO (correo)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE HORARIO(
	empleado_dia INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	dia varchar(15) NOT NULL,
	hora_ini TIME NOT NULL,
	hora_fin TIME NOT NULL,
	horas INT NOT NULL,
	id_empleado INT NOT NULL,
	CONSTRAINT FK_EMPLEADO_HORARIO FOREIGN KEY(id_empleado)
	REFERENCES EMPLEADO (id_empleado)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE BITACORA_HISTORIAL(
	id_historial INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	fecha DATETIME NOT NULL,
	correo VARCHAR(64),
	cambio_realizado VARCHAR(50),
	detalles VARCHAR(50),
	id_afectados INT NOT NULL
);
GO

CREATE TABLE DOCTOR(
	id_doctor INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	cedula_profesional VARCHAR(10) NOT NULL,
	id_empleado INT NOT NULL,
	no_consultorio INT NOT NULL,
	id_especialidad INT NOT NULL,
	FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado),
	FOREIGN KEY (no_consultorio) REFERENCES CONSULTORIO(no_consultorio),
	FOREIGN KEY (id_especialidad) REFERENCES ESPECIALIDAD(id_especialidad)
);
GO

CREATE TABLE FARMACEUTICO(
	id_farmaceutico INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	id_empleado INT NOT NULL,
	CONSTRAINT FK_EMPLEADO_FARMACEUTICO FOREIGN KEY(id_empleado)
	REFERENCES EMPLEADO (id_empleado)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE VENTA(
	folio_venta INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	fecha DATETIME NOT NULL,
	subtotal DECIMAL(10,2) NOT NULL,    
	id_farmaceutico INT NOT NULL,
	id_paciente INT NULL,
	FOREIGN KEY (id_farmaceutico) REFERENCES FARMACEUTICO(id_farmaceutico),
	FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id_paciente)
);
GO

CREATE TABLE DETALLE_VENTA(
	id_detalle INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	folio_venta INT NOT NULL,
	id_medicamento INT NULL, 
	id_servicio INT NULL,    
	cantidad INT NOT NULL,
	precio_unitario DECIMAL(10,2) NOT NULL, 
	FOREIGN KEY (folio_venta) REFERENCES VENTA(folio_venta),
	FOREIGN KEY (id_medicamento) REFERENCES MEDICAMENTO(id_medicamento),
	FOREIGN KEY (id_servicio) REFERENCES SERVICIO(id_servicio)
);
GO

CREATE TABLE HISTORIAL_MEDICO(
	id_historial_medico INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	padecimiento VARCHAR(30) NULL,
	presion_sistolica INT NOT NULL,
	presion_diastolica INT NOT NULL,
	peso DECIMAL(5,2) NOT NULL,
	estatura DECIMAL(5,2) NOT NULL,
	fecha DATE NOT NULL,
	oxigenacion INT NOT NULL,
	detalles VARCHAR(150),
	id_paciente INT NOT NULL,
	CONSTRAINT FK_PACIENTE_HISTORIAL FOREIGN KEY(id_paciente)
	REFERENCES PACIENTE (id_paciente)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE CITA(
	folio_cita INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	fecha_cita DATETIME NOT NULL,
	fecha_solicitud DATETIME NOT NULL,
	id_estado INT NOT NULL,
	fecha_fin_cita DATETIME NOT NULL,
	id_paciente INT NOT NULL,
	no_consultorio INT NOT NULL,
	id_doctor INT NOT NULL,
	FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id_paciente),
	FOREIGN KEY (no_consultorio) REFERENCES CONSULTORIO(no_consultorio),
	FOREIGN KEY (id_doctor) REFERENCES DOCTOR(id_doctor),
	FOREIGN KEY (id_estado) REFERENCES ESTADO_CITA(id_estado)
);
GO

CREATE TABLE PAGO(
	folio_pago INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	total DECIMAL(10,2) NOT NULL,
	fecha DATETIME NOT NULL,
	folio_cita INT NOT NULL,
	CONSTRAINT FK_CITA_PAGO FOREIGN KEY(folio_cita)
	REFERENCES CITA (folio_cita)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE RECETA(
	folio_receta INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	fecha DATE NOT NULL,
	diagnostico VARCHAR(40) NOT NULL,
	folio_cita INT NOT NULL,
	CONSTRAINT FK_CITA_RECETA FOREIGN KEY(folio_cita)
	REFERENCES CITA (folio_cita)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE RECETA_MEDICAMENTO(
	folio_receta_med INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	detalles VARCHAR(60) NOT NULL,
	folio_receta INT NOT NULL,
	id_medicamento INT NOT NULL,
	CONSTRAINT FK_RECETA_RECETAMED FOREIGN KEY(folio_receta)
	REFERENCES RECETA (folio_receta)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_MEDICAMENTO_RECETA FOREIGN KEY(id_medicamento)
	REFERENCES MEDICAMENTO (id_medicamento)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
GO

CREATE TABLE ESTADO_SOLICITUD (
    id_estado INT IDENTITY(1,1) PRIMARY KEY,
    detalle VARCHAR(30) NOT NULL -- 'Pendiente', 'Aceptado', 'Rechazado'
);
GO

CREATE TABLE SOLICITUD_EMPLEADO (
    id_solicitud INT IDENTITY(1,1) PRIMARY KEY,
    fecha_solicitud DATETIME DEFAULT GETDATE(),
    correo VARCHAR(64) NOT NULL,
    contrasenia VARCHAR(255) NOT NULL,
    rol_solicitado VARCHAR(20) NOT NULL, -- 'Medico', 'Enfermera'
    curp VARCHAR(18) NOT NULL,
    primer_nombre VARCHAR(30) NOT NULL,
    segundo_nombre VARCHAR(30) NULL,
    a_paterno VARCHAR(30) NOT NULL,
    a_materno VARCHAR(30) NULL,
    genero VARCHAR(15) NOT NULL,
    telefono VARCHAR(13) NOT NULL,
    id_estado INT NOT NULL DEFAULT 1, -- Por defecto entra como 1 (Pendiente)
    CONSTRAINT FK_SOLICITUD_ESTADO FOREIGN KEY (id_estado)
    REFERENCES ESTADO_SOLICITUD (id_estado)
);
GO

SELECT * FROM USUARIO;
SELECT * FROM PACIENTE;